### ISSUE TITLE
Consider an "unformat" API

### ISSUE THREAD

**Issue by chowey** [nosir/cleave-zen#4]
I'd like to get the "raw value" from an input field.

So when I do e.g. `formatCreditCard` or `formatNumeral`, it would be useful to "undo" the format and get back the raw result when I'm ready to POST my data somewhere.

I like to have my numbers raw.

I would expect there to be the inverse of the "format" API, to "unformat" it. So just like we have `formatNumeral(value, options)` I'd expect there to be a `rawNumeral(value, options)` (or some other name) to "unformat" the number. Then I can use `parseFloat` to get the raw number.

Also for e.g. card numbers, I'd like to store the raw number without delimiters. So there should be a `rawCreditCard(value, options)`.

This is a feature request.

**Comment by nosir** [comment]
Good point, will add this soon.

**Comment by nosir** [comment]
`unformat` functions added in release `0.0.16`
e.g. 
https://github.com/nosir/cleave-zen/blob/main/docs/modules.md#unformatcreditcard
https://github.com/nosir/cleave-zen/blob/main/docs/modules.md#unformatnumeral
